version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"    
    networks:
      - app-tier      
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ../DockerVolumes:/var/lib/mysql

  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-tier
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'

volumes:
  mydata: